=== darianderson/EpamPractice-1/data/practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/veretelnyk/GunsPractice/entity"
            xmlns:tns="http://nure.ua/veretelnyk/GunsPractice/entity"
            version="1.1">

    <!-- Root element for storing all guns-->
    <xsd:element name="Guns">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Gun" type="tns:Gun" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- basic building element -->
    <xsd:complexType name="Gun">
        <xsd:sequence>

            <xsd:element name="Model" type="xsd:string"/>
            <xsd:element name="Handy" type="tns:Handy"/>
            <xsd:element name="Origin" type="xsd:string"/>
            <xsd:element name="TTC" type="tns:TTC"/>
            <xsd:element name="Material" type="xsd:string"/>

        </xsd:sequence>
    </xsd:complexType>


    <!-- tactical and technical characteristics -->
    <xsd:complexType name="TTC">
        <xsd:sequence>

            <xsd:element name="Distance" type="tns:Distance"/>
            <xsd:element name="SightingRange" type="xsd:integer"/>
            <xsd:element name="Collar" type="xsd:boolean"/>
            <xsd:element name="Optics" type="xsd:boolean"/>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Distance">
        <xsd:choice>
            <xsd:element name="short" type="tns:short"/>
            <xsd:element name="middle" type="tns:middle"/>
            <xsd:element name="long" type="tns:long"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="Handy">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:enumeration value="one-hand"/>
            <xsd:enumeration value="two-hand"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="short">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="500"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="middle">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="500"/>
            <xsd:maxInclusive value="1000"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="long">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1000"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

<!--
Check with and without tns

bin/xjc
xjc -d input.xsd
path in ""
-->

=== darianderson/EpamPractice-1/data/practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against input.xsd XML schema-->

<guns:Guns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:guns="http://nure.ua/veretelnyk/GunsPractice/entity"
        xsi:schemaLocation="http://nure.ua/veretelnyk/GunsPractice/entity input.xsd">
    <Gun>
        <Model>AK-47</Model>
        <Handy>two-hand</Handy>
        <Origin>Soviet Union</Origin>
        <TTC>
            <Range>
                <!--Type>long</Type-->
                <Distance>
                    <long>1500</long>
                </Distance>
            </Range>
            <SightingRange>800</SightingRange>
            <Collar>true</Collar>
            <Optics>false</Optics>
        </TTC>
        <Material>Metal</Material>

        <!--Model></Model>
        <Handy></Handy>
        <Origin></Origin>
        <TTC>
            <Range>
                <Type></Type>
                <Distance></Distance>
            </Range>
            <SightingRange></SightingRange>
            <Collar></Collar>
            <Optics></Optics>
        </TTC>
        <Material></Material-->
    </Gun>
</guns:Guns>

=== darianderson/EpamPractice-1/practice7/data/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against input.xsd XML schema-->

<guns:Guns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:guns="http://nure.ua/veretelnyk/GunsPractice/entity"
        xsi:schemaLocation="http://nure.ua/veretelnyk/GunsPractice/entity input.xsd">
    <Gun>
        <Model>AK-47</Model>
        <Handy>two-hand</Handy>
        <Origin>Soviet Union</Origin>

        <TTC>
            <Distance>
                <long>1500</long>
            </Distance>
            <SightingRange>800</SightingRange>
            <Collar>true</Collar>
            <Optics>false</Optics>
        </TTC>

        <Material>Metal</Material>
    </Gun>

    <Gun>
        <Model>M16</Model>
        <Handy>two-hand</Handy>
        <Origin>USA</Origin>

        <TTC>
            <Distance>
                <middle>800</middle>
            </Distance>
            <SightingRange>600</SightingRange>
            <Collar>true</Collar>
            <Optics>false</Optics>
        </TTC>

        <Material>Metal</Material>
    </Gun>

    <Gun>
        <Model>Barrett M82</Model>
        <Handy>two-hand</Handy>
        <Origin>USA</Origin>

        <TTC>
            <Distance>
                <long>2000</long>
            </Distance>
            <SightingRange>1500</SightingRange>
            <Collar>true</Collar>
            <Optics>true</Optics>
        </TTC>

        <Material>Metal</Material>
    </Gun>



</guns:Guns>
